services:
  - type: web
    name: ticket-saas-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://aasmttsibsovngwdtyqe.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhc210dHNpYnNvdm5nd2R0eXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDMzNTcsImV4cCI6MjA1ODA3OTM1N30.mHzdNIVWawLZX__jGvjH0tlHTftALoyDxI7nFmrOU6Y
      - key: ALLOWED_ORIGINS
        value: https://your-app.vercel.app
